### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at:

### ISSUE THREAD

**Issue by husligc** [dimisdas/instabot.py#4]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug    NOTE*  not sure if bug but something isn't working correctly
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue
ever since the code fix for "edge media error", we have been experiencing the following error randomly.

I don't have the actual error.log but the error message is the following.
This is an example of the like/comment that works then after so many of them the bot dies with the following messages.  I have included errors from two different runs.

14.01.2019_10:17 Get Media by tag: xxxxxxxxxxxx
14.01.2019_10:17 Removing already liked medias..
14.01.2019_10:17 Trying to like media: 1956748584017117033
14.01.2019_10:17 Liked: 1956748584017117033. Like #12.
14.01.2019_10:17 Trying to comment: 1956748381934232493
14.01.2019_10:17 Write: "jf;ljafljfafj;lajfl;afjl;fjl ?". #8.
14.01.2019_10:18 Trying to like media: 1956747678064722632
14.01.2019_10:18 Liked: 1956747678064722632. Like #13.

Traceback (most recent call last):
  File "myfilename", line 63, in <module>
    bot.new_auto_mod()
  File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 901, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 1018, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 1043, in check_exisiting_comment
    all_data = json.loads(re.search('window._sharedData = (.*?);', check_comment.text, re.DOTALL).group(1))['entry_data']['PostPage'][0] #window._sharedData = (.*?);
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 18183 (char 18182)
14.01.2019_10:20 Logout: likes - 13, follow - 0, unfollow - 0, comments - 8.
14.01.2019_10:20 Bot work time: 0:20:54.270379
14.01.2019_10:20 Logout success!

I restart the bot and it will run for a random number of likes / comments and die again.
Note the column number of the unterminated string is always different.

Traceback (most recent call last):
  File "myfilename", line 63, in <module>
    bot.new_auto_mod()
  File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 901, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 1018, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 1043, in check_exisiting_comment
    all_data = json.loads(re.search('window._sharedData = (.*?);', check_comment.text, re.DOTALL).group(1))['entry_data']['PostPage'][0] #window._sharedData = (.*?);
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 12180 (char 12179)
14.01.2019_12:51 Logout: likes - 53, follow - 0, unfollow - 0, comments - 34.
14.01.2019_12:51 Bot work time: 1:29:40.872635
14.01.2019_12:51 Logout success!

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by husligc** [comment]
i added this issue to the main issue list.
